- tools/prepare-libs.sh
I expect there is some discussion of whether this is the appropriate place to put this, but having an auto-generated versioning will be very helpful for troubleshooting.
> Add a define into sdkconfig.h that shows the exact idf commit of build

- .github/workflows/cron.yml
- .github/workflows/push.yml
- .github/workflows/repository_dispatch.yml
- build.sh
- tools/archive-build.sh
- tools/config.sh
- tools/cron.sh
- tools/install-esp-idf.sh
- tools/prepare-libs.sh
- tools/push-to-arduino.sh
- tools/repository_dispatch.sh
- tools/update-components.sh
Implements
- builds based on branch or commit
- saving build artefacts
- remote triggered builds
- periodically triggered builds
- builds can push to a branch and create PR
- more
> Build system overhaul

- tools/copy-libs.sh
> Integrate PR https://github.com/espressif/arduino-esp32/pull/6464

- .gitignore
- tools/copy-bootloader.sh
Allows the bootloaders to be flashed with esptool v4 on devices with different size flash
> Do not append digest to the bootloader bin

- tools/copy-libs.sh
…ESP32, C3 and S2 when using Platformio
Replaces https://github.com/espressif/arduino-esp32/pull/7141
> Use flash_mode for memory_type when memory_type is not set for

- README.md
jq is not preinstalled on a fresh Ubuntu installation.
> README.md: Add jq as dependency.

- main/Kconfig.projbuild
Adding this config will let other libraries (Rainmaker, Insights, etc) compile code that is only required for Arduino.
> Added config to detect lib_builder is used.

- configs/pio_end.txt
- configs/pio_start.txt
- tools/config.sh
- tools/copy-libs.sh
This PR contains updates for the upcoming core v3.0:
- Precompiled SDK libraries are now moved to a new `framework-arduinoespressif32-libs` package
- Refactored frequent `env.BoardConfig()` calls for better performance
cc @me-no-dev
> Update PlatformIO build script templates

- CMakeLists.txt
- README.md
- tools/update-components.sh
Build tflite-micro libraries. 
cc: @vikramdattu
> Added tflite-micro component

- .github/workflows/push.yml
Actions checkout updated from v2 to v3 to silence deprecated warning
> Fix warnings from outdated GH actions

- CMakeLists.txt
- build.sh
- main/idf_component.yml
- tools/copy-libs.sh
- tools/update-components.sh
This PR makes 2 main changes:
1- Fixes CMakeFiles and the build.sh + copy-libs.sh to work with WSL Ubuntu
2- Removes RainMaker and other git-cloned component in order to use them from the Managed Components Registry.
This change demands that Arduino Repository also change in orde to reflect the use of Managed Components.
https://github.com/espressif/arduino-esp32/pull/8842
> Using most IDF Managed Components instead of git-clone

- tools/copy-libs.sh
Added manual copy of Zigbee and Zboss libraries for each SoC as automatic build by enabling in SDK config is not possible to include all zigbee modes (libraries).
Follow up PR (WIP) in Arduino-esp32 repository to add Zigbee and Zboss as managed components.
> Copy Zigbee + Zboss libraries

- main/idf_component.yml
- tools/update-components.sh
Removes git clone esp-dl from update-component.sh
Moves esp-dl to managed components for Lib Builder layer only - S3 only - from master GH
> esp-dl as managed component

- README.md
Adding a link to the Lib Builder documentation. It should be useful for users to have link directly for with more information.
> Adding link to the Documentation

- tools/config.sh
The `arch` alias/command is not available on many distros. By replacing it with `uname -m` we can make the lib-builder more distro agnostic and enable compilation in distros like Arch.
https://man7.org/linux/man-pages/man1/arch.1.html
> Replace "arch" with "uname -m"

- tools/config_editor/README.md
- tools/config_editor/app.py
Fixes UI readme by adding a code block in the usage section.
Also improves target pre-configuration by converting arguments to lower case.
> Fix UI Readme and improve target selection

- tools/copy-libs.sh
from `platformio-build.py` and Arduino build formula.
The `-fdebug-prefix-map` entrys are left overs from the IDF compile process and are not needed or of any use for Arduino. The litter and may do harm since path file length could be too long when compiling.
This PR removes all such entries.
> rm `-fdebug-prefix-map` entrys from "CCFLAGS"

- tools/copy-libs.sh
bt, esp-tflite-micro and openthread
> Strip the debug info from some libs to save space

- patches/mmu_map.diff
- tools/install-esp-idf.sh
Connected to: https://github.com/espressif/arduino-esp32/issues/9936
> Add temporary fix for mmu map and late init of psram

- patches/lwip_max_tcp_pcb.diff
- tools/install-esp-idf.sh
Fixes: https://github.com/espressif/arduino-esp32/issues/9954
> Add patch to fix the maximum number of TCP PCBs in TIME_WAIT

- build.sh
ERROR: Some components (espressif/esp-dsp) in the "managed_components"  directory were modified on the disk since the last run of the CMake.
> Fix ESP-DSP breaking the build

- configs/pio_start.txt
@me-no-dev 
currently zigbee libs are not added in Platformio build process.
The needed libs are added with adding the corresponding define in Platformio `build_flags`
Something like:
```
build_flags  =  -DZIGBEE_MODE_ZCZR
```
for Zigbee Coordinator.
> add zigbee libs for Platformio

- tools/install-arduino.sh
- tools/install-esp-idf.sh
Trying to checkout to a branch that does not exist yet fails.
Moved fetch to before checkout to avoid this situation. Also added `--all` flag to get the correct branches no matter how the remotes are set up.
> fix(install): Fetch before checkout to avoid errors

- .github/workflows/docker.yml
- .github/workflows/push.yml
- tools/docker/Dockerfile
Fix Dockerfile to use requirements.txt and test docker build in PRs that might change the docker build result.
Also optimizes the push workflow.
> Fix Dockerfile and test docker build in PRs

- tools/docker/README.md
- tools/docker/run.ps1
- tools/docker/run.sh
Add missing docker tag to 5.1 branch
> fix(docker): Add docker tag to run scripts in 5.1 branch

- tools/copy-libs.sh
This PR add $EXCLUDE_LIBS variable, which can be used to exclude libraries which are added to link flags.
Zigbee libraries are removed, as the link is added by selection in AArduino IDE tools menu -> Zigbee Mode
---
Before submitting a Pull Request, please ensure the following:
> fix(zigbee): Unlink the zigbee libs

- .github/workflows/cron.yml
- .github/workflows/cron_build.yml
- tools/check-deploy-needed.sh
- tools/config.sh
Allows manually creating new libs without waiting for IDF commits.
Also use pagination to avoid issues with finding the IDF commit.
Tested in my fork
> fix(libs): Allow for manual rebuilding and fix commit checking

- tools/config.sh
Add missing fallback value to `AR_USER`. This is required when running locally.
Closes #247
Locally
> fix(config): Add fallback value to AR_USER

- configs/defconfig.esp32c6
- configs/defconfig.esp32h2
Disable OpenThread DNS64 Client for the ESP32-C6 and ESP32-H2.
There is a conflic after an ESP-IDF change to OpenThread.
https://github.com/espressif/esp-idf/issues/15069
Using artifacts based on issue https://github.com/espressif/arduino-esp32/issues/10754
> Update defconfig.esp32c6 and defconfig.esp32h2 to disable OpenThread DNS64

- configs/pioarduino_end.txt
Add missing define to pioarduino script
Closes #256
> fix(pioarduino): Add missing define

- tools/config.sh
- tools/push-to-arduino.sh
When downloading and uploading release files it sometimes can fail. Add delays and improve error handling to mitigate this issue.
> fix(upload): Add delays and improve error handling

- tools/copy-libs.sh
Update exclude libs for Zigbee targeting 3.2.x release (IDF v5.4)
https://github.com/espressif/arduino-esp32/pull/10890
> fix(zigbee): Exclude correct libs for 1.6.2 version

- tools/copy-libs.sh
This PR fixes zigbee-sdk libs, that were not excluded properly.
ZIGBEE LIBS:
`esp_zb_api_ed` changed to `esp_zb_api.ed`
ZBOSS LIBS:
added `zboss_port.native`
> fix(zigbee): Update exclude libs in script

- tools/docker/Dockerfile
Fixes errors in docker image building by bumping versions.
CI
> fix(docker): Bump base image

- tools/copy-libs.sh
As all SOCs now compile with Zigbee enabled, exclude all possible zigbee libs.
> fix(libs): Add also zcrz and remote zb libs to exclude

- tools/copy-libs.sh
There is a Macro for Resolve Include in Matter that has been treated in a different way in Matter 1.4 Managed Component.
This PR solves this issue.
https://github.com/espressif/esp32-arduino-lib-builder/pull/281
CI
> fixes Matter 1.4 Resolve Include Macro

- .github/workflows/cron_build.yml
- .github/workflows/docker.yml
- .github/workflows/push.yml
- .github/workflows/repository_dispatch.yml
To avoid supply chain attacks, lock actions used in workflows to commit hash rather than tag.
Also improve readability of files.
> ci(workflows): Lock actions to commits and improve readability

- CMakeLists.txt
Moving from C++17 to C++2a that works with Matter.
> Update CMakeLists.txt to use gnu++2a instead of 17

- main/idf_component.yml
Updates esp_matter component to 1.4.1 which:
Fixes the `asset()` issue with `-DNDEBUG`
Fixes many warning messages when compiling sketches that use Arduino Matter Library. 
ESP_MATTER
https://github.com/espressif/arduino-esp32/issues/11166
CI + Artifacts
> feat(esp_matter): updates esp_matter component to 1.4.1

- tools/install-esp-idf.sh
ESP-IDF installation process generates tens of thousands of carriage returns `\r` that are printed as new lines, making the CI log very hard to navigate.
This pull request includes a small change to the `tools/install-esp-idf.sh` script. The change improves the user experience by adding a message to indicate that the ESP-IDF installation process has started and suppresses the installation script's output. Error messages should not be affected.
Impact can be checked here:
https://github.com/espressif/esp32-arduino-lib-builder/actions/runs/15450574032/job/43491389484?pr=300#step:4:116
> fix(logging): Silence stdout from IDF installation

- .github/workflows/docker.yml
Updated docker workflow to create a tag for the master branch based on the information in `./tools/config.sh`. Now when changes are pushed to the master branch both `latest` and `release/vx.x` will be pushed
Tested in fork.
> fix(docker): Fix docker image tagging

- configs/defconfig.esp32c5
- main/idf_component.yml
Enables Matter for the ESP32-C5 based on libraries generted for https://github.com/espressif/arduino-esp32/pull/11531
https://github.com/espressif/arduino-esp32/pull/11531
CI Artifacts
> Feat(matter): enable Matter for the C5

- configs/defconfig.esp32c5
ESP32-C5 has few SRAM available.
Matter consumes a lot of SRAM with its static variable declarations and object constructors.
After testing many combinations, the only way to get esp32c5 working with Arduino and Matter Library is by only using it with OpenThread and BLE commissioning.
This PR sets this configuration.
None
CI Artifacts
> feat(matter): matter with thread + ble works fine

- build.sh
- configs/builds.json
This pull request adds support for the `esp_sr` feature to the `esp32p4` build target and ensures that the `srmodels_bin` build step runs for both `esp32s3` and `esp32p4` targets. These changes help extend speech recognition capabilities and streamline the build process for new hardware.
Build process updates:
* Modified `build.sh` to run the `srmodels_bin` build step for both `esp32s3` and `esp32p4` targets, ensuring speech recognition models are included for the new hardware.
Feature configuration updates:
* Added the `esp_sr` feature to the `esp32p4` target in `configs/builds.json`, enabling speech recognition support for this platform.
To be merged after https://github.com/espressif/arduino-esp32/pull/11785
> Enable srmodel export for ESP32-P4
